import type { Metadata } from "next";
import "./globals.css";
import {Footer} from "@/app/components/Footer";
import {Header} from "@/app/components/Header";
export const metadata: Metadata = {
  title: "Annonce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
